module.exports = {
  EMPTY_RESPONSE: 'EMPTY_RESPONSE',
  MALFORMED_RESPONSE_CHUNK: 'MALFORMED_RESPONSE_CHUNK',
  RANDOM_DATA_THEN_CLOSE: 'RANDOM_DATA_THEN_CLOSE',
  CONNECTION_RESET_BY_PEER: 'CONNECTION_RESET_BY_PEER',
  TIME_WAIT: 'TIME_WAIT'
}
